// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndggidkhgekvqjwfghex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kZ2dpZGtoZ2VrdnFqd2ZnaGV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTU1OTgsImV4cCI6MjA2NTQ3MTU5OH0.VwWNcI4ojeevU2v8C9fA-iYCbD6mOAdwTGBSF5llfy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);